# Generated by Django 5.1.7 on 2025-03-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_customuser_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient'), ('lab_technician', 'Lab Technician')], default='patient', max_length=20),
        ),
    ]
