# Generated by Django 5.1.7 on 2025-04-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0005_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('admin', 'Admin'), ('patient', 'Patient'), ('lab_technician', 'Lab Technician')], default='patient', max_length=20),
        ),
    ]
