# Generated by Django 5.1.7 on 2025-03-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_disease_doctors_labtech_laboratory_lab_tech'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='swahili_name',
            field=models.CharField(default='swahili', max_length=50),
        ),
    ]
