# Generated by Django 5.1.7 on 2025-05-08 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_testorder_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
    ]
