# Generated by Django 5.1.6 on 2025-04-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_symptom_swahili_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescribedtest',
            name='test',
        ),
        migrations.AddField(
            model_name='prescribedtest',
            name='test',
            field=models.ManyToManyField(related_name='medicat_tests', to='patient.medicaltest'),
        ),
    ]
