# Generated by Django 5.1.5 on 2025-04-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_symptom_swahili_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
