# Generated by Django 5.1.7 on 2025-05-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_remove_laboratory_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='prescribed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
