# Generated by Django 5.1.5 on 2025-04-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_laboratory_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='description',
            field=models.CharField(default='Ready to Serve you at best standards', max_length=1000),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='email',
            field=models.CharField(default='voicepowered@lab.com', max_length=100),
        ),
    ]
