# Generated by Django 5.1.6 on 2025-04-20 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_remove_prescribedtest_test_prescribedtest_test'),
        ('patient', '0005_laboratory_description_laboratory_email'),
    ]

    operations = [
    ]
