# Generated by Django 5.1.7 on 2025-06-13 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_alter_doctor_specialization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtech',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='labtech',
            name='years_of_experience',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
