# Generated by Django 5.1.5 on 2025-04-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_testorder'),
        ('patient', '0008_alter_appointment_status'),
    ]

    operations = [
    ]
