# Generated by Django 5.1.7 on 2025-04-25 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_doctor_profile_image_laboratory_profile_image_and_more'),
        ('patient', '0009_merge_0007_testorder_0008_alter_appointment_status'),
    ]

    operations = [
    ]
