# Generated by Django 5.1.6 on 2025-04-25 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_alter_patient_date_of_birth_alter_patient_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='prescribed_test',
        ),
        migrations.AddField(
            model_name='testresult',
            name='test_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='patient.testorder'),
        ),
    ]
