# Generated by Django 5.1.7 on 2025-04-29 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_prescription_test_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='prescribed_test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='patient.prescribedtest'),
        ),
    ]
