# Generated by Django 5.1.6 on 2025-05-05 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_testresult_prescribed_test'),
        ('patient', '0016_alter_patient_user'),
    ]

    operations = [
    ]
